-- Generated by fix_post_coordinates.py
-- 
-- Total corrections: 170

-- Post #26: Toronto
--   Coordinates: (43.6532, -79.3832)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 26;

-- Post #27: Montreal
--   Coordinates: (45.5017, -73.5673)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 27;

-- Post #28: Paris
--   Coordinates: (48.8566, 2.3522)
--   Current: country.kyrgyzstan (KG)
--   Correct: country.france (FR)
UPDATE post SET country_id = 115 WHERE id = 28;

-- Post #29: Hanói
--   Coordinates: (21.0285, 105.8542)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 29;

-- Post #30: Florença
--   Coordinates: (43.7696, 11.2558)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 30;

-- Post #32: Paris
--   Coordinates: (48.8566, 2.3522)
--   Current: country.kyrgyzstan (KG)
--   Correct: country.france (FR)
UPDATE post SET country_id = 115 WHERE id = 32;

-- Post #33: Bangkok
--   Coordinates: (13.7563, 100.5018)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 33;

-- Post #34: Nova York
--   Coordinates: (40.7128, -74.006)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 34;

-- Post #35: Chiang Mai
--   Coordinates: (18.7061, 98.9817)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 35;

-- Post #37: Bangkok
--   Coordinates: (13.7563, 100.5018)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 37;

-- Post #38: Hanói
--   Coordinates: (21.0285, 105.8542)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 38;

-- Post #39: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 39;

-- Post #41: Toronto
--   Coordinates: (43.6532, -79.3832)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 41;

-- Post #42: Marrakech
--   Coordinates: (31.6295, -7.9811)
--   Current: country.norway (NO)
--   Correct: country.morocco (MA)
UPDATE post SET country_id = 35 WHERE id = 42;

-- Post #43: Florença
--   Coordinates: (43.7696, 11.2558)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 43;

-- Post #44: Cairo
--   Coordinates: (30.0444, 31.2357)
--   Current: country.bahrain (BH)
--   Correct: country.egypt (EG)
UPDATE post SET country_id = 15 WHERE id = 44;

-- Post #46: Marrakech
--   Coordinates: (31.6295, -7.9811)
--   Current: country.norway (NO)
--   Correct: country.morocco (MA)
UPDATE post SET country_id = 35 WHERE id = 46;

-- Post #48: Ho Chi Minh
--   Coordinates: (10.8231, 106.6297)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 48;

-- Post #49: Hanói
--   Coordinates: (21.0285, 105.8542)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 49;

-- Post #50: Ho Chi Minh
--   Coordinates: (10.8231, 106.6297)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 50;

-- Post #51: Chiang Mai
--   Coordinates: (18.7061, 98.9817)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 51;

-- Post #52: Roma
--   Coordinates: (41.9028, 12.4964)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 52;

-- Post #54: Hanói
--   Coordinates: (21.0285, 105.8542)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 54;

-- Post #55: Ho Chi Minh
--   Coordinates: (10.8231, 106.6297)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 55;

-- Post #56: Paris
--   Coordinates: (48.8566, 2.3522)
--   Current: country.kyrgyzstan (KG)
--   Correct: country.france (FR)
UPDATE post SET country_id = 115 WHERE id = 56;

-- Post #57: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 57;

-- Post #58: Cidade do Cabo
--   Coordinates: (-33.9249, 18.4241)
--   Current: country.peru (PE)
--   Correct: country.south_africa (ZA)
UPDATE post SET country_id = 46 WHERE id = 58;

-- Post #59: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 59;

-- Post #60: Paris
--   Coordinates: (48.8566, 2.3522)
--   Current: country.kyrgyzstan (KG)
--   Correct: country.france (FR)
UPDATE post SET country_id = 115 WHERE id = 60;

-- Post #62: Cairo
--   Coordinates: (30.0444, 31.2357)
--   Current: country.bahrain (BH)
--   Correct: country.egypt (EG)
UPDATE post SET country_id = 15 WHERE id = 62;

-- Post #63: Bangkok
--   Coordinates: (13.7563, 100.5018)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 63;

-- Post #64: Osaka
--   Coordinates: (34.6937, 135.5023)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 64;

-- Post #65: São Francisco
--   Coordinates: (37.7749, -122.4194)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 65;

-- Post #66: Hanói
--   Coordinates: (21.0285, 105.8542)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 66;

-- Post #67: Toronto
--   Coordinates: (43.6532, -79.3832)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 67;

-- Post #68: Auckland
--   Coordinates: (-36.8485, 174.7633)
--   Current: country.cuba (CU)
--   Correct: country.new_zealand (NZ)
UPDATE post SET country_id = 177 WHERE id = 68;

-- Post #69: Montreal
--   Coordinates: (45.5017, -73.5673)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 69;

-- Post #70: Cidade do Cabo
--   Coordinates: (-33.9249, 18.4241)
--   Current: country.peru (PE)
--   Correct: country.south_africa (ZA)
UPDATE post SET country_id = 46 WHERE id = 70;

-- Post #71: Auckland
--   Coordinates: (-36.8485, 174.7633)
--   Current: country.cuba (CU)
--   Correct: country.new_zealand (NZ)
UPDATE post SET country_id = 177 WHERE id = 71;

-- Post #72: Paris
--   Coordinates: (48.8566, 2.3522)
--   Current: country.kyrgyzstan (KG)
--   Correct: country.france (FR)
UPDATE post SET country_id = 115 WHERE id = 72;

-- Post #73: Hanói
--   Coordinates: (21.0285, 105.8542)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 73;

-- Post #74: Auckland
--   Coordinates: (-36.8485, 174.7633)
--   Current: country.cuba (CU)
--   Correct: country.new_zealand (NZ)
UPDATE post SET country_id = 177 WHERE id = 74;

-- Post #75: Florença
--   Coordinates: (43.7696, 11.2558)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 75;

-- Post #76: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 76;

-- Post #77: Melbourne
--   Coordinates: (-37.8136, 144.9631)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 77;

-- Post #78: Tóquio
--   Coordinates: (35.6762, 139.6503)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 78;

-- Post #79: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 79;

-- Post #80: Sydney
--   Coordinates: (-33.8688, 151.2093)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 80;

-- Post #81: Roma
--   Coordinates: (41.9028, 12.4964)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 81;

-- Post #82: Cidade do Cabo
--   Coordinates: (-33.9249, 18.4241)
--   Current: country.peru (PE)
--   Correct: country.south_africa (ZA)
UPDATE post SET country_id = 46 WHERE id = 82;

-- Post #83: Sydney
--   Coordinates: (-33.8688, 151.2093)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 83;

-- Post #84: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 84;

-- Post #85: Bangkok
--   Coordinates: (13.7563, 100.5018)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 85;

-- Post #86: Auckland
--   Coordinates: (-36.8485, 174.7633)
--   Current: country.cuba (CU)
--   Correct: country.new_zealand (NZ)
UPDATE post SET country_id = 177 WHERE id = 86;

-- Post #87: Tóquio
--   Coordinates: (35.6762, 139.6503)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 87;

-- Post #88: Cairo
--   Coordinates: (30.0444, 31.2357)
--   Current: country.bahrain (BH)
--   Correct: country.egypt (EG)
UPDATE post SET country_id = 15 WHERE id = 88;

-- Post #89: Cairo
--   Coordinates: (30.0444, 31.2357)
--   Current: country.bahrain (BH)
--   Correct: country.egypt (EG)
UPDATE post SET country_id = 15 WHERE id = 89;

-- Post #90: Nova York
--   Coordinates: (40.7128, -74.006)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 90;

-- Post #91: Montreal
--   Coordinates: (45.5017, -73.5673)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 91;

-- Post #92: Florença
--   Coordinates: (43.7696, 11.2558)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 92;

-- Post #93: Roma
--   Coordinates: (41.9028, 12.4964)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 93;

-- Post #94: Florença
--   Coordinates: (43.7696, 11.2558)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 94;

-- Post #95: Tóquio
--   Coordinates: (35.6762, 139.6503)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 95;

-- Post #97: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 97;

-- Post #98: Florença
--   Coordinates: (43.7696, 11.2558)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 98;

-- Post #99: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 99;

-- Post #100: Cidade do Cabo
--   Coordinates: (-33.9249, 18.4241)
--   Current: country.peru (PE)
--   Correct: country.south_africa (ZA)
UPDATE post SET country_id = 46 WHERE id = 100;

-- Post #101: Roma
--   Coordinates: (41.9028, 12.4964)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 101;

-- Post #103: Chiang Mai
--   Coordinates: (18.7061, 98.9817)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 103;

-- Post #105: Marrakech
--   Coordinates: (31.6295, -7.9811)
--   Current: country.norway (NO)
--   Correct: country.morocco (MA)
UPDATE post SET country_id = 35 WHERE id = 105;

-- Post #106: Cidade do Cabo
--   Coordinates: (-33.9249, 18.4241)
--   Current: country.peru (PE)
--   Correct: country.south_africa (ZA)
UPDATE post SET country_id = 46 WHERE id = 106;

-- Post #107: São Francisco
--   Coordinates: (37.7749, -122.4194)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 107;

-- Post #108: Toronto
--   Coordinates: (43.6532, -79.3832)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 108;

-- Post #109: Tóquio
--   Coordinates: (35.6762, 139.6503)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 109;

-- Post #110: Bangkok
--   Coordinates: (13.7563, 100.5018)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 110;

-- Post #111: Florença
--   Coordinates: (43.7696, 11.2558)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 111;

-- Post #112: Toronto
--   Coordinates: (43.6532, -79.3832)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 112;

-- Post #114: Toronto
--   Coordinates: (43.6532, -79.3832)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 114;

-- Post #115: Tóquio
--   Coordinates: (35.6762, 139.6503)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 115;

-- Post #116: Ho Chi Minh
--   Coordinates: (10.8231, 106.6297)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 116;

-- Post #117: Bangkok
--   Coordinates: (13.7563, 100.5018)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 117;

-- Post #118: Sydney
--   Coordinates: (-33.8688, 151.2093)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 118;

-- Post #120: Bangkok
--   Coordinates: (13.7563, 100.5018)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 120;

-- Post #121: Montreal
--   Coordinates: (45.5017, -73.5673)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 121;

-- Post #122: Bangkok
--   Coordinates: (13.7563, 100.5018)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 122;

-- Post #123: Cidade do Cabo
--   Coordinates: (-33.9249, 18.4241)
--   Current: country.peru (PE)
--   Correct: country.south_africa (ZA)
UPDATE post SET country_id = 46 WHERE id = 123;

-- Post #124: Nova York
--   Coordinates: (40.7128, -74.006)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 124;

-- Post #125: Hanói
--   Coordinates: (21.0285, 105.8542)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 125;

-- Post #126: Marrakech
--   Coordinates: (31.6295, -7.9811)
--   Current: country.norway (NO)
--   Correct: country.morocco (MA)
UPDATE post SET country_id = 35 WHERE id = 126;

-- Post #127: Tóquio
--   Coordinates: (35.6762, 139.6503)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 127;

-- Post #128: Marrakech
--   Coordinates: (31.6295, -7.9811)
--   Current: country.norway (NO)
--   Correct: country.morocco (MA)
UPDATE post SET country_id = 35 WHERE id = 128;

-- Post #129: São Francisco
--   Coordinates: (37.7749, -122.4194)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 129;

-- Post #131: Roma
--   Coordinates: (41.9028, 12.4964)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 131;

-- Post #133: Ho Chi Minh
--   Coordinates: (10.8231, 106.6297)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 133;

-- Post #134: Paris
--   Coordinates: (48.8566, 2.3522)
--   Current: country.kyrgyzstan (KG)
--   Correct: country.france (FR)
UPDATE post SET country_id = 115 WHERE id = 134;

-- Post #135: Melbourne
--   Coordinates: (-37.8136, 144.9631)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 135;

-- Post #136: Montreal
--   Coordinates: (45.5017, -73.5673)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 136;

-- Post #138: Sydney
--   Coordinates: (-33.8688, 151.2093)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 138;

-- Post #139: Paris
--   Coordinates: (48.8566, 2.3522)
--   Current: country.kyrgyzstan (KG)
--   Correct: country.france (FR)
UPDATE post SET country_id = 115 WHERE id = 139;

-- Post #141: Bangkok
--   Coordinates: (13.7563, 100.5018)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 141;

-- Post #142: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 142;

-- Post #144: Osaka
--   Coordinates: (34.6937, 135.5023)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 144;

-- Post #145: Paris
--   Coordinates: (48.8566, 2.3522)
--   Current: country.kyrgyzstan (KG)
--   Correct: country.france (FR)
UPDATE post SET country_id = 115 WHERE id = 145;

-- Post #146: Hanói
--   Coordinates: (21.0285, 105.8542)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 146;

-- Post #147: Roma
--   Coordinates: (41.9028, 12.4964)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 147;

-- Post #148: Osaka
--   Coordinates: (34.6937, 135.5023)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 148;

-- Post #150: Paris
--   Coordinates: (48.8566, 2.3522)
--   Current: country.kyrgyzstan (KG)
--   Correct: country.france (FR)
UPDATE post SET country_id = 115 WHERE id = 150;

-- Post #151: Montreal
--   Coordinates: (45.5017, -73.5673)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 151;

-- Post #152: Florença
--   Coordinates: (43.7696, 11.2558)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 152;

-- Post #153: Melbourne
--   Coordinates: (-37.8136, 144.9631)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 153;

-- Post #154: Montreal
--   Coordinates: (45.5017, -73.5673)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 154;

-- Post #155: São Francisco
--   Coordinates: (37.7749, -122.4194)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 155;

-- Post #156: Cairo
--   Coordinates: (30.0444, 31.2357)
--   Current: country.bahrain (BH)
--   Correct: country.egypt (EG)
UPDATE post SET country_id = 15 WHERE id = 156;

-- Post #157: Roma
--   Coordinates: (41.9028, 12.4964)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 157;

-- Post #160: Chiang Mai
--   Coordinates: (18.7061, 98.9817)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 160;

-- Post #161: Cairo
--   Coordinates: (30.0444, 31.2357)
--   Current: country.bahrain (BH)
--   Correct: country.egypt (EG)
UPDATE post SET country_id = 15 WHERE id = 161;

-- Post #164: Melbourne
--   Coordinates: (-37.8136, 144.9631)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 164;

-- Post #165: São Francisco
--   Coordinates: (37.7749, -122.4194)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 165;

-- Post #167: Hanói
--   Coordinates: (21.0285, 105.8542)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 167;

-- Post #168: Sydney
--   Coordinates: (-33.8688, 151.2093)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 168;

-- Post #169: Melbourne
--   Coordinates: (-37.8136, 144.9631)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 169;

-- Post #170: Tóquio
--   Coordinates: (35.6762, 139.6503)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 170;

-- Post #171: Auckland
--   Coordinates: (-36.8485, 174.7633)
--   Current: country.cuba (CU)
--   Correct: country.new_zealand (NZ)
UPDATE post SET country_id = 177 WHERE id = 171;

-- Post #175: Bangkok
--   Coordinates: (13.7563, 100.5018)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 175;

-- Post #176: Sydney
--   Coordinates: (-33.8688, 151.2093)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 176;

-- Post #177: Hanói
--   Coordinates: (21.0285, 105.8542)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 177;

-- Post #178: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 178;

-- Post #179: Chiang Mai
--   Coordinates: (18.7061, 98.9817)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 179;

-- Post #180: Chiang Mai
--   Coordinates: (18.7061, 98.9817)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 180;

-- Post #181: Hanói
--   Coordinates: (21.0285, 105.8542)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 181;

-- Post #182: Cairo
--   Coordinates: (30.0444, 31.2357)
--   Current: country.bahrain (BH)
--   Correct: country.egypt (EG)
UPDATE post SET country_id = 15 WHERE id = 182;

-- Post #183: Osaka
--   Coordinates: (34.6937, 135.5023)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 183;

-- Post #184: São Francisco
--   Coordinates: (37.7749, -122.4194)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 184;

-- Post #185: Marrakech
--   Coordinates: (31.6295, -7.9811)
--   Current: country.norway (NO)
--   Correct: country.morocco (MA)
UPDATE post SET country_id = 35 WHERE id = 185;

-- Post #186: Ho Chi Minh
--   Coordinates: (10.8231, 106.6297)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 186;

-- Post #187: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 187;

-- Post #188: Roma
--   Coordinates: (41.9028, 12.4964)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 188;

-- Post #189: Sydney
--   Coordinates: (-33.8688, 151.2093)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 189;

-- Post #190: Marrakech
--   Coordinates: (31.6295, -7.9811)
--   Current: country.norway (NO)
--   Correct: country.morocco (MA)
UPDATE post SET country_id = 35 WHERE id = 190;

-- Post #191: Melbourne
--   Coordinates: (-37.8136, 144.9631)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 191;

-- Post #192: Nova York
--   Coordinates: (40.7128, -74.006)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 192;

-- Post #194: Cairo
--   Coordinates: (30.0444, 31.2357)
--   Current: country.bahrain (BH)
--   Correct: country.egypt (EG)
UPDATE post SET country_id = 15 WHERE id = 194;

-- Post #195: Melbourne
--   Coordinates: (-37.8136, 144.9631)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 195;

-- Post #196: Ho Chi Minh
--   Coordinates: (10.8231, 106.6297)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 196;

-- Post #197: Osaka
--   Coordinates: (34.6937, 135.5023)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 197;

-- Post #198: Toronto
--   Coordinates: (43.6532, -79.3832)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 198;

-- Post #199: Auckland
--   Coordinates: (-36.8485, 174.7633)
--   Current: country.cuba (CU)
--   Correct: country.new_zealand (NZ)
UPDATE post SET country_id = 177 WHERE id = 199;

-- Post #200: Cidade do Cabo
--   Coordinates: (-33.9249, 18.4241)
--   Current: country.peru (PE)
--   Correct: country.south_africa (ZA)
UPDATE post SET country_id = 46 WHERE id = 200;

-- Post #201: Roma
--   Coordinates: (41.9028, 12.4964)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 201;

-- Post #202: Florença
--   Coordinates: (43.7696, 11.2558)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 202;

-- Post #203: Auckland
--   Coordinates: (-36.8485, 174.7633)
--   Current: country.cuba (CU)
--   Correct: country.new_zealand (NZ)
UPDATE post SET country_id = 177 WHERE id = 203;

-- Post #204: Florença
--   Coordinates: (43.7696, 11.2558)
--   Current: country.bosnia_herzegovina (BA)
--   Correct: country.italy (IT)
UPDATE post SET country_id = 121 WHERE id = 204;

-- Post #205: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 205;

-- Post #206: Bangkok
--   Coordinates: (13.7563, 100.5018)
--   Current: country.vanuatu (VU)
--   Correct: country.thailand (TH)
UPDATE post SET country_id = 95 WHERE id = 206;

-- Post #207: Cidade do México
--   Coordinates: (19.4326, -99.1332)
--   Current: country.malta (MT)
--   Correct: country.mexico (MX)
UPDATE post SET country_id = 163 WHERE id = 207;

-- Post #210: Cairo
--   Coordinates: (30.0444, 31.2357)
--   Current: country.bahrain (BH)
--   Correct: country.egypt (EG)
UPDATE post SET country_id = 15 WHERE id = 210;

-- Post #211: Sydney
--   Coordinates: (-33.8688, 151.2093)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 211;

-- Post #212: Auckland
--   Coordinates: (-36.8485, 174.7633)
--   Current: country.cuba (CU)
--   Correct: country.new_zealand (NZ)
UPDATE post SET country_id = 177 WHERE id = 212;

-- Post #213: Nova York
--   Coordinates: (40.7128, -74.006)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 213;

-- Post #215: Cidade do Cabo
--   Coordinates: (-33.9249, 18.4241)
--   Current: country.peru (PE)
--   Correct: country.south_africa (ZA)
UPDATE post SET country_id = 46 WHERE id = 215;

-- Post #216: Auckland
--   Coordinates: (-36.8485, 174.7633)
--   Current: country.cuba (CU)
--   Correct: country.new_zealand (NZ)
UPDATE post SET country_id = 177 WHERE id = 216;

-- Post #217: Auckland
--   Coordinates: (-36.8485, 174.7633)
--   Current: country.cuba (CU)
--   Correct: country.new_zealand (NZ)
UPDATE post SET country_id = 177 WHERE id = 217;

-- Post #218: Montreal
--   Coordinates: (45.5017, -73.5673)
--   Current: country.niger (NE)
--   Correct: country.canada (CA)
UPDATE post SET country_id = 152 WHERE id = 218;

-- Post #219: Ho Chi Minh
--   Coordinates: (10.8231, 106.6297)
--   Current: country.chile (CL)
--   Correct: country.vietnam (VN)
UPDATE post SET country_id = 101 WHERE id = 219;

-- Post #220: São Francisco
--   Coordinates: (37.7749, -122.4194)
--   Current: country.colombia (CO)
--   Correct: country.united_states (US)
UPDATE post SET country_id = 170 WHERE id = 220;

-- Post #221: Melbourne
--   Coordinates: (-37.8136, 144.9631)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 221;

-- Post #222: Tóquio
--   Coordinates: (35.6762, 139.6503)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 222;

-- Post #223: Cairo
--   Coordinates: (30.0444, 31.2357)
--   Current: country.bahrain (BH)
--   Correct: country.egypt (EG)
UPDATE post SET country_id = 15 WHERE id = 223;

-- Post #224: Osaka
--   Coordinates: (34.6937, 135.5023)
--   Current: country.denmark (DK)
--   Correct: country.japan (JP)
UPDATE post SET country_id = 71 WHERE id = 224;

-- Post #225: Melbourne
--   Coordinates: (-37.8136, 144.9631)
--   Current: country.democratic_republic_congo (CD)
--   Correct: country.australia (AU)
UPDATE post SET country_id = 171 WHERE id = 225;

-- Validation query
-- Expected: 225 total posts, 170 corrected
-- SELECT COUNT(*) FROM post;