package com.sora.backend.model;

public enum NotificationType {
    NEW_FOLLOWER,
    USER_FOLLOWED,
    TRAVEL_PERMISSION_INVITATION,
    TRAVEL_PERMISSION_ACCEPTED,
    TRAVEL_PERMISSION_DECLINED,
    TRAVEL_PERMISSION_REVOKED,
    POST_LIKED,
    POST_COMMENTED,
    COMMENT_REPLIED
}