spring:
  application:
    name: sora-backend
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sora?currentSchema=public}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:sora}
    password: ${DB_PASSWORD:sora}
      
  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    validate-on-migrate: ${FLYWAY_VALIDATE_ON_MIGRATE:true}
    
  messages:
    basename: messages
    encoding: UTF-8

  web:
    locale: pt_BR
    locale-resolver: fixed
    
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:50MB}

jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345678901234567890}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:2592000000}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dummy}
  api-key: ${CLOUDINARY_API_KEY:dummy}
  api-secret: ${CLOUDINARY_API_SECRET:dummy}
  secure: true

file:
  upload:
    max-size: ${UPLOAD_MAX_SIZE:10MB}
    allowed-types: ${ALLOWED_TYPES:image/jpeg,image/png,image/webp}

openstreetmap:
  base-url: ${OSM_BASE_URL:https://nominatim.openstreetmap.org}
  user-agent: ${OSM_USER_AGENT:SoraApp/1.0}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://10.0.2.2:8080}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,PATCH,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
  max-age: ${CORS_MAX_AGE:3600}

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.sora.backend: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    tags-sorter: alpha

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/sora?currentSchema=public
    driverClassName: org.postgresql.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  
  flyway:
    enabled: true
    baseline-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: prod
      
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sora}?currentSchema=public
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:sora}
    password: ${DB_PASSWORD:sora}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  
  flyway:
    enabled: true
    baseline-on-migrate: false
    validate-on-migrate: true
      
logging:
  level:
    com.sora.backend: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN